version: "3"
services:
    postgres:
         image: postgres:9.3
         environment:
           POSTGRES_USER: team77
           POSTGRES_PASSWORD: mintic2020.
           POSTGRES_DB: postgres
         ports:
           - "5432:5432"
    python_app:
         build: 
           context: ./python_app
           dockerfile: Dockerfile
         ports:
           - 8787:8787
         depends_on:
           - postgres
    jupyter:
          build: 
           context: ./jupyter
           dockerfile: Dockerfile
          volumes:
            - /home:/home/jovyan/work
          ports: 
            - "8888:8888"
