version: "3"
#DOCKER_HOST tcp://172.31.39.76
services:
    postgres:
         image: postgres:9.3
         environment:
           POSTGRES_USER: team77
           POSTGRES_PASSWORD: mintic2020.
           POSTGRES_DB: postgres
         ports:
           - "5432:5432"
    python_app:
         build: 
           context: ./python_app
           dockerfile: Dockerfile
         ports:
           - 8787:8787
         depends_on:
           - postgres
    jupyter:
          build: 
           context: ./jupyter
           dockerfile: Dockerfile
          environment:
           GRANT_SUDO: "yes"
          volumes:
            - /home:/home/jovyan/work
            #- <ruta a mis documentos>:/home/jovyan/work # En windows
          ports: 
            - "8888:8888"
            - "8050:8050"
    pgadmin:
         container_name: pgadmin_container
         image: dpage/pgadmin4
         environment:
           PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-team77@pgadmin.org}
           PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-mintic2020.}
         volumes:
           - /home/:/var/lib/pgadmin/storage/home/
         ports:
           - "${PGADMIN_PORT:-5050}:80"
