version: "3"
services:
    postgres:
         image: postgres:9.3
         environment:
           POSTGRES_USER: team77
           POSTGRES_PASSWORD: mintic2020.
           POSTGRES_DB: postgres
         ports:
           - "5432:5432"
    jupyter:
          image: jupyter/scipy-notebook
          volumes:
            - /home:/home/jovyan/work
          ports: 
            - "8888:8888"
