# Labels for feature importance plots

temp = {'timejail_day': 'Time in jail (days)',
        'age': 'Age',
        'MARITALSTATUS_FREE UNION': 'Free Union',
        'DELITO_COMP_AGRA_CALF_THEFT': 'Crime: Theft Agravado Calificado',
        'JAILNAME_CAMIS ACACIAS': 'Jail: Acacias',
        'JAILNAME_COMPLEJO CARCELARIO Y PENITENCIARIO DE JAMUNDI-CONDENADOS': 'Jail: Jamundi',
        'JAILNAME_COMPLEJO CARCELARIO Y PENITENCIARIO METROPOLITANO DE BOGOTA': 'Jail: Bogota',
        'JAILNAME_EPMSC MEDELLIN': 'Jail: Medellin',
        'JAILNAME_EPMSC-RM PASTO': 'Jail: Pasto',
        'REGIONALNME_CENTRAL': 'Region: Central',
        'REGIONALNME_NORTE': 'Region: North',
        'SEVERITY': 'Severity score',
        'LIFEXP': 'Life expectancy at birth',
        'ACTIVIDADES_ESTUDIO': 'Study in jail',
        'EDUC_LEVEL_First cycle': 'Primary school cycle 1', 
        'HIJOS_MENORES': 'With children', 
        'MARITALSTATUS_UNDEFINED': 'Undefined marital status', 
        'DELITO_COMP_CALF_THEFT' : 'Crime: Theft Calificado', 
        'EDUC_LEVEL_Second cycle': 'Primary school cycle 2', 
        'EDUC_LEVEL_Fourth cycle': 'Primary school cycle 4',
        'DELITO_COMP_OTHER': 'Crime: other', 
        'ACTIVIDADES_TRABAJO': 'Work in jail', 
        'SHDI':'Sub-national HDI', 
        'EDINDEX':'Educational index', 
        'INCINDEX':'Income index',
        'REGIONALNME_NOROESTE':'Region: Noroeste',
        'ESCH':'Expected years of schooling', 
        'MSCH':'Mean years of schooling', 
        'POP':'Population', 
        'GENERO': 'Gender',
        'ADULTO_MAYOR':'Elderly',
        'DELITO_COMP_HOMICIDE': 'Crime: Homicide',
        'DELITO_COMP_AGRA_HOMICIDE': 'Crime: Homicide Agravado',
        'HEALTHINDEX':'Health index', 
        'JAILNAME_EPMSC DUITAMA': 'Jail: Duitama',
        'JAILNAME_EPMSC CALI (ERE)': 'Jail: Cali',
        'JAILNAME_EPC LA ESPERANZA DE GUADUAS': 'Jail: Guaduas',
        'JAILNAME_EC BOGOTA': 'Jail: Bogota',
        'GNIC':'GNI per capita (US 2011 PPP)',
        'DELITO_COMP_CALF_THEFT':'Crime: Theft Calificado',
        'DELITO_COMP_MANUFACTURING TRAFFIC OR SUPPORT OF NARCOTICS':'Crime: Manufacturing, traffic and support narcotics',
        'DELITO_COMP_TRAFFIC MANUFACTURE AND PORTION OF FIREARMS OR AMMUNITIONS': 'Crime: Traffic, manufacture and possession\nof firearms or ammunitions',
        'DELITO_COMP_TENT_AGRA_THEFT': 'Crime: Theft: Agravado Tentativa',
        'DELITO_COMP_THEFT': 'Crime: Theft',
        'MARITALSTATUS_SINGLE': 'Single',
        'JAILNAME_EPMSC NEIVA': 'Jail: Neiva',
        'REGIONALNME_VIEJO CALDAS': 'Region: Viejo Caldas',
        'DELITO_COMP_AGRA_THEFT':'Crime: Theft Agravado',
        'JAILNAME_EPMSC PEREIRA (ERE)':'Jail: Pereira',
        'JAILNAME_EPMSC MANIZALES':'Jail: Manizales',
        'DELITO_COMP_TENT_CALF_THEFT':'Crime: Theft Tentativa Calificado',
        'DELITO_COMP_TENT_AGRA_CALF_THEFT': 'Crime: Theft Tentativa Agravado Calificado',
        'JAILNAME_CPMS BUCARAMANGA (ERE)': 'Jail: Bucaramanga',
        'REGIONALNME_OCCIDENTE': 'Region: Occidente'}